### ISSUE TITLE
select all from rdfs/Class not working

### ISSUE THREAD

**Issue by jakep36** [fluree/db#311]
I'm unable to run:
```javascript
{
    "ledger": "fluree-jld/bug00002",
    "query": {
        "select": { "?u": ["*"] },
        "where": [
            ["?u", "rdf:type", "rdfs:Class"]
        ]
    }
}
``` 
on the HTTP API server

Below is my clojure repl trying to get it to run using our db library. Getting this error:
```
{:type clojure.lang.ExceptionInfo
   :message "Undefined RDF type specified: http://www.w3.org/2000/01/rdf-schema#Class"
   :data {:status 400, :error :db/invalid-query}
   :at [fluree.db.query.fql.parse$parse_class invokeStatic "parse.cljc" 238]}
```

```clojure
(ns user
  (:require [fluree.db.json-ld.api :as fluree]
            [fluree.db.util.core :as util]))

(defn deref!
  "Derefs promise p and throws if the result is an exception, returns it otherwise."
  [p]
  (let [res @p]
    (if (util/exception? res)
      (throw res)
      res)))

(def default-context
  {:id     "@id"
   :type   "@type"
   :schema "http://schema.org/"
   :ex     "http://example.org/ns/"
   :rdfs   "http://www.w3.org/2000/01/rdf-schema#"
   :rdf    "http://www.w3.org/1999/02/22-rdf-syntax-ns#"})


(def conn @(fluree/connect {:method :file
                            :storage-path "data"}))

(def initial-tx {:context default-context
                 :id :ex/coco
                 :type :schema/Person
                 :schema/name "Coco"})


(def ledger-name "fluree-jld/bug000000")

(comment ;; if empty ledger
  (def db (fluree/db (deref! (fluree/create conn ledger-name))))


  (def staged-db (deref! (fluree/stage db initial-tx)))
  (def committed-db (deref! (fluree/commit! staged-db))))


;; query helper
(defn query [q]
  (let [db     (->> ledger-name (fluree/load conn) deref! fluree/db)]
    (deref (fluree/query db q))))

;; this query giving the error
(query  {:context default-context
           :select {'?s [:*]}
           :where [['?s :rdf/type :rdfs/Class]]})
```

**Comment by zonotope** [comment]
@jakep36 or @bplatz: how important is it that we maintain casing for rdf type names? 

This bug was caused by the expanded iri from the query expanded to "http:// ... schema#class", while the iri we have stored in the db for that predicate is "http:// ... schema#Class". 

I could just normalize everything to lowercase since iris are case insensitive, but then if a person entered `:schema/Person` in a query, they'd get back `:schema/person`. Does that matter?

**Comment by bplatz** [comment]
IRIs are case sensitive. It appears the query uses capitalized ‘Class’ - is it the expansion that is lower casing it?

**Comment by zonotope** [comment]
My mistake on the case sensitivity. My test queries were using lowercase, so that's why it didn't work on my side. When I use the correct casing  though, it looks like it works for me with the latest:

```
user> @(fluree/query db {:context default-context
                         :select '{?s [:*]}
                         :where '[[?s :rdf/type :rdfs/Class]]})
[{:id :schema/Person, :rdf/type [:rdfs/Class]}
 {:id :f/Context, :rdf/type [:rdfs/Class]}]
```

@jakep36 do you have access to the latest db code and can you try it out?

**Comment by jakep36** [comment]
@zonotope I'll try it with the latest http-api-server that @cap10morgan updated. Thanks!

**Comment by jakep36** [comment]
I'm still getting: 
```
#error {:cause "Undefined RDF type specified: http://www.w3.org/2000/01/rdf-schema#Class"
        :data {:status 400, :error :db/invalid-query}
        :via
        [{:type clojure.lang.ExceptionInfo
          :message "Undefined RDF type specified: http://www.w3.org/2000/01/rdf-schema#Class"
          :data {:status 400, :error :db/invalid-query}
          :at [fluree.db.query.fql.parse$parse_class invokeStatic "parse.cljc" 242]}]
``` 
wondering if something in my state or setup is not the same. Also getting that in the http-api-server with the updated db commit sha.

**Comment by zonotope** [comment]
Here's my entire repl session:
```clojure
user> (require '[fluree.db.json-ld.api :as fluree])
nil
user> (def default-context
        {:id     "@id"
         :type   "@type"
         :schema "http://schema.org/"
         :ex     "http://example.org/ns/"
         :rdfs   "http://www.w3.org/2000/01/rdf-schema#"
         :rdf    "http://www.w3.org/1999/02/22-rdf-syntax-ns#"})
#'user/default-context
user> (require '[fluree.db.did :as did])
nil
user> (def default-private-key
        "8ce4eca704d653dec594703c81a84c403c39f262e54ed014ed857438933a2e1c")
#'user/default-private-key
user> (def did (did/private->did-map default-private-key))
#'user/did
user> (def conn @(fluree/connect-memory {:defaults {:context default-context
                                                    :did     did}}))
#'user/conn
user> (def ledger @(fluree/create conn "test/rdfs-class"))
#'user/ledger
user> (def db @(fluree/stage ledger {:context default-context
                                     :id :ex/coco
                                     :type :schema/Person
                                     :schema/name "Coco"}))
#'user/db
user> @(fluree/query db {:context default-context
                         :select '{?s [:*]}
                         :where '[[?s :rdf/type :rdfs/Class]]})
[{:id :schema/Person, :rdf/type [:rdfs/Class]}
 {:id "https://ns.flur.ee/ledger#Context", :rdf/type [:rdfs/Class]}]
```

I notice that you're using the file connection and I'm using memory. I'll try it with the file conn next.

**Comment by zonotope** [comment]
Yep, that did it. It has something to do with the file conn. I'll dig in to that.

**Comment by jakep36** [comment]
I don't have the default-private-key stuff. Is that necessary?

**Comment by zonotope** [comment]
Maybe not. I just included it because it was in the test helpers, but it might be a relic. In any case, the problem is definitely in the file connection loading/persistence.

**Comment by cap10morgan** [comment]
> Maybe not. I just included it because it was in the test helpers, but it might be a relic. In any case, the problem is definitely in the file connection loading/persistence.

I might have this already fixed in a local branch that I'm turning into a PR shortly.

**Comment by zonotope** [comment]
> > Maybe not. I just included it because it was in the test helpers, but it might be a relic. In any case, the problem is definitely in the file connection loading/persistence.
> 
> I might have this already fixed in a local branch that I'm turning into a PR shortly.

I cherry picked Wes's commit with his file connection improvements onto my branch but it didn't fix the issue unfortunately. I will continue to dig in and find the fix.

**Comment by bplatz** [comment]
@zonotope This issue is with the HTTP-API server and I got a near identical use case (searching for owl:Class) working for our demo. I'll put a PR in for it there and suggest someone verify it addresses the issue.

**Comment by jakep36** [comment]
@bplatz I see the issue outside of the http-api as well like in the replication code above. Is there more than one issue here?

**Comment by bplatz** [comment]
> @bplatz I see the issue outside of the http-api as well like in the replication code above. Is there more than one issue here?

Looks like it. The HTTP-API issue is that it uses the Clojure keyword context, not the string-based context. That is here now for reference: https://github.com/fluree/http-api-gateway/pull/9/files
